# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install SSH client
      run: |
        sudo apt-get install -y openssh-client
    # - name: Add SSH key
    #   uses: shimataro/ssh-key-action@v2
    #   with:
    #     key: ${{ secrets.SSH_PRIVATE_KEY }}
    #     name: gcp_vm
    #     known_hosts: ${{ secrets.SSH_HOST }}
    - name: Add SSH key
      run: |
        mkdir ~/.ssh
        echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/gcp_vm
        chmod ~/.ssh/gcp_vm
        ssh-keyscan ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
    - name: Test connection
      run: |
        ssh -i ~/.ssh/gcp_vm -o StrictHostKeyChecking=no ${{secrets.SSH_USER}}@${{ secrets.SSH_HOST}} "echo 'Hello World'"

        
      
