on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]


jobs:
  build-and-test:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v4
      - name: "Setup python 3.11"
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'
      - name: "Install dependencies"
        run: |
          pip install -r app/requirements.txt
      - name: "Test the app"
        env:
          CALL_MY_NAME: 'Tegar'
        run: |
          pytest app/test_main.py
  deploy:
    runs-on: "ubuntu-latest"
    needs: ["build-and-test"]
    steps:
      - uses: actions/checkout@v4
      # - name: "Build and push image"
      #   run: |
      #     docker login --username Tegarr123 --password ${{ secrets.PAT_DOCKER_REGISTRY}} ghcr.io
      #     docker build . -f ./app.Dockerfile -t ghcr.io/tegarr123/fastapi-image:latest
      #     docker push ghcr.io/tegarr123/fastapi-image:latest
      - name: "Install ssh key"
        uses: "shimataro/ssh-key-action@v2"
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY}}
          name: gcp_vm
          known_hosts: ${{secrets.SSH_HOST}}
          config: |
            Host target
              HostName ${{secrets.SSH_HOST}}
              User ${{secrets.SSH_USER}}
              IdentityFile ~/.ssh/gcp_vm
      - name: "Set known hosts"
        run: |
          ssh-keyscan -H ${{secrets.SSH_HOST}} >> ~/.ssh/known_hosts
      - name: "Test SSH"
        run: |
          ssh target echo 'Hello World'
      

      
      
