on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]


jobs:
  build:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v4
      - name: "Setup python 3.11"
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'
      - name: "Install dependencies"
        run: |
          pip install -r app/requirements.txt
      - name: "Test the app"
        env:
          CALL_MY_NAME: 'Tegar'
        run: |
          pytest app/test_main.py
      - name: "Build and push image"
        run: |
          docker login --username Tegarr123 --password ${{ secrets.PAT_DOCKER_REGISTRY}} ghcr.io
          docker build . -f ./app.Dockerfile -t ghcr.io/tegarr123/fastapi-image:latest
          docker push ghcr.io/tegarr123/fastapi-image:latest

      
      
